#!/usr/bin/env bash

## Adapted from Aditya Shakya

MENU="$(rofi slate -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -10 -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Misc Termsyn 12" <<< " Lock| Reboot| Shutdown| Cancel")"
case "$MENU" in
    *Lock)      xset s activate ;;
    *Reboot)    systemctl reboot ;;
    *Shutdown)  systemctl -i poweroff ;;
esac
