#!/usr/bin/env bash

# pgrep ibus-daemon > /dev/null || ibus-daemon &
pgrep sxhkd > /dev/null || sxhkd &
dunst &

pkill polybar
polybar top &
polybar bottom &

amixer sset Master 50%

xsetroot -cursor_name left_ptr &
xset r rate 250 69

bspc monitor -d 1-dev 2-doc 3-cfg 4-fun 5-life 6-chat 7-media 8-idle 9-hide

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config window_gap 0

# Material darker colors
bspc config normal_border_color "#808080"
bspc config active_border_color "#808080"
# bspc config focused_border_color "#89ddff"
bspc config focused_border_color "#c3e88d"
bspc config presel_feedback_color "#bd93f9"

# Extra padding for polybar
# bspc config ignore_ewmh_struts true
# bspc config top_padding 27
# bspc config bottom_padding 27

bspc config automatic_scheme spiral
bspc config removal_adjustment true
bspc config initial_polarity first_child

# bspc config split_ratio         0.52

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_action3 resize_side
bspc config click_to_focus any
bspc config pointer_follows_monitor true

bspc rule -a Pinentry state=floating center=on follow=on
bspc rule -a float-term state=floating center=on follow=on

bspc rule -a zoom desktop='6-chat' follow=on
bspc rule -a zoom:zoom:zoom state=floating follow=off

bspc rule -a slack desktop='6-chat' follow=on
bspc rule -a discord desktop='6-chat' follow=on

bspc rule -a spotify desktop='7-media' follow=on
