#! /bin/sh

sxhkd &

xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width        4
bspc config window_gap          15

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     false

bspc config click_to_focus any

bspc rule -a kitty   desktop='^1' follow=on
bspc rule -a Firefox desktop='^2' follow=on
