#!/usr/bin/env bash

set -euf

tms="$(dirname "$0")"

read -r -d '' cmds <<'EOF' || true
kb-rate
polybar-launch
mon-auto
mon-haunter
mon-mirror
EOF

prompt () {
  # rofi -p "$1 >" -dmenu
  "$tms"/picker --prompt="$1 > "
}

err () {
    notify-send -t 3000 -u critical "$0" "$*"
}


if [ "$#" -ne 1 ]; then
  cmd="$(echo "$cmds" | prompt "cmd")"
else
  cmd="$1"
fi

if [ -z "$cmd" ]; then
  echo "Usage: $0 [<cmd>]"
  exit 1
fi

case "$cmd" in
  kb-rate)
    xset r rate 250 69
    ;;
  polybar-launch)
    ~/.config/polybar/launch.sh
    ;;
  mon-auto)
    xrandr --auto
    ;;
  mon-haunter)
    xrandr --output DP-2-2 --off && \
      xrandr --output DP-2-2 --primary --auto --output eDP-1 --right-of DP-2-2
    ;;
  mon-mirror)
    xrandr --output DP-2-2 --off && \
      xrandr --output eDP-1 --primary --auto --output DP-2-2 --auto --same-as eDP-1
    ;;
  *)
    err "Unknown cmd: $cmd"
    exit 1
    ;;
esac
