#!/usr/bin/env bash

set -euf

if ! command -v wmctrl >/dev/null 2>/dev/null ; then
  notify-send -u critical -t 3000 "$0" "Missing dependency: wmctrl"
  exit 1
fi

wmctrl -d | ~/.local/tms/picker --with-nth=-1 | cut -d ' ' -f 1 | while read -r d ; do
  wmctrl -s "$d"
done
