#!/usr/bin/env bash

# Janky command-line interface to spotify/spotifyd/whatever is playing
# via playerctl/spt

set -euf

if [ "$#" -ne "1" ]; then
  echo "Need to specify command"
  return 1
fi

case "$1" in
  brightness-up)
    brightnessctl set 10%+
    ;;
  brightness-down)
    brightnessctl set 10%-
    ;;
  vol-up)
    amixer sset Master 10%+
    ;;
  vol-down)
    amixer sset Master 10%-
    ;;
  vol-mute)
    amixer sset Master 0%
    ;;
  play | play-pause | pause)
    playerctl --player=spotify,spotifyd,%d "$1"
    ;;
  prev | previous | p)
    playerctl --player=spotify,spotifyd,%d previous
    ;;
  next | n)
    playerctl --player=spotify,spotifyd,%d next
    ;;
  here)
    # NOTE: very flaky
    systemctl --user restart spotifyd
    sleep 1
    spt playback --tranfer "$(hostname)-spotifyd)"
    ;;
  like) ;;
esac
