#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip  🔋 ⚡ 
# yabai -m config status_bar_space_icon        ?
yabai -m config status_bar_clock_icon        🕒

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          2
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               cmd + ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               12
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   8

# floating
yabai -m rule --add app="^Enpass$" manage=off sticky=on topmost=on

# Space 2: terminal

# Space 3: communications
yabai -m rule --add app="^Messages$" space=3
yabai -m rule --add app="^Wavebox$" space=3

# Space 4: browser
yabai -m rule --add app="^Google Chrome$" space=4

# Space 5: office + creative
yabai -m rule --add app="^MuseScore 3$" space=5
yabai -m rule --add app="^Microsoft Word$" space=5
yabai -m rule --add app="^Microsoft Powerpoint$" space=5
yabai -m rule --add app="^Microsoft Excel$" space=5
yabai -m rule --add app="^Bitwig Studio$" space=5

# Space 6: unused
yabai -m rule --add app="VirtualBox" space=6 manage=off

# Space 7: monitoring
yabai -m rule --add app="^Activity Monitor$" space=7
yabai -m rule --add app="^System Preferences$" space=7 manage=off

# Space 8: music
yabai -m rule --add app="^iTunes$" space=8

echo "yabai configuration loaded.."
