#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI
yabai -m config status_bar_power_icon_strip  🔋 ⚡ 
# yabai -m config status_bar_space_icon        ?
yabai -m config status_bar_clock_icon        🕒

# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          2
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
# yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               12
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   8

# floating
yabai -m rule --add app="^Enpass$" manage=off sticky=on topmost=on
yabai -m rule --add app="^Stickies$" manage=off sticky=on topmost=on
yabai -m rule --add app="^Activity Monitor$" manage=off sticky=on topmost=on
yabai -m rule --add app="^System Preferences$" manage=off sticky=on topmost=on
yabai -m rule --add app="^VirtualBox$" manage=off sticky=on topmost=on

# Space 1: terminal

# Space 2: communications
yabai -m rule --add app="^Messages$" space=2
yabai -m rule --add app="^Wavebox$" space=2
yabai -m rule --add app="^Slack$" space=2
yabai -m rule --add app="^WhatsApp$" space=2
yabai -m rule --add app="^Caprine$" space=2
yabai -m rule --add app="^Discord$" space=2
yabai -m rule --add app="^zoom.us$" space=2

# Space 3: browser
yabai -m rule --add app="^Google Chrome$" space=3
yabai -m rule --add app="^Firefox$" space=3

# Space 4: office + creative
yabai -m rule --add app="^MuseScore 3$" space=4
yabai -m rule --add app="^Microsoft Word$" space=4
yabai -m rule --add app="^Microsoft Powerpoint$" space=4
yabai -m rule --add app="^Microsoft Excel$" space=4
yabai -m rule --add app="^Bitwig Studio$" space=4
yabai -m rule --add app="^Code$" space=4

# Space 5: music
yabai -m rule --add app="^Music$" space=5
yabai -m rule --add app="^Google Play Music Desktop Player$" space=5
yabai -m rule --add app="^YouTube Music$" space=5

echo "yabai configuration loaded.."
